# -*- coding: utf-8 -*-
"""파이썬 Lecture2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17-gXeOha_fxlSMIjtWnIvT3T7hQC0NMJ
"""

def get_area(radius):
  area = 3.14*radius**2
  return area

result = get_area(3)
print("반지름이 3인 원의 면적 =", result)

def a():
  return 2,3

x = a()
print(x)
print(type(x)) #tuple 타입은 수정이 불가능함

def sub():
  pass #나중에 작성할 경우 pass 키워드를 사용

def test(*a): #튜플 타입
  print(a)

test(10,20,30)

#가변인수
def varfunc(*args):
  print(args)

print("하나의 값으로 호출")
varfunc(10)

print("여러 개의 값으로 호출")
varfunc(10,20,30)

#딕셔너리
def myfunc(**kwargs):
  print(kwargs)
  result = ""
  for arg in kwargs.values():
    result += arg
  return result
  
print(myfunc(ace="Hi!",bee="Mr.",name="Kim"))

#순환호출 예제
def factorial(n):
  if n == 1:
    return(1)
  else:
    return n * factorial(n-1)

n = eval(input("정수를 입력하시오:"))
print(n, "!=", factorial(n))

#함수 안에서 전역 변수 변경하기
gx = 100
g = 200

def myfunc():
  gx = g
  print(gx)

myfunc()
print(gx)

#zip() 함수

questions = ['name', 'quest', 'color']
answers = ['Kim', '파이썬', 'blue']
for q, a in zip(questions, answers):
  print(f"What is your {q}? It is {a}")

#최소값 최대값 제거하기 예제

scores=[10.0,9.0,8.3,7.1,3.0,9.0]
print("제거 전", scores)
scores.remove(max(scores))
scores.remove(min(scores))
print("제거 후", scores)

squares = []

for x in range(10):
  squares.append(x*x)

print(squares)

squares = [x*x for x in range(10)]

mprices = []
prices = [135, -545, 922, 356, -992, 217]

for i in prices:
  if i>0:
    mprices.append(i)
  else:
    mprices.append(0)

print(mprices)

numbers = []

for x in['a', 'b', 'c']:
  for y in['x', 'y', 'z']:
    numbers.append(x+y)
print(numbers)

#위랑 똑같은 코드

aaaa = [x+y for x in['a','b','c'] for y in['x','y','z']]
print(aaaa)

